// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"
)

const countCorrespondents = `-- name: CountCorrespondents :one
SELECT COUNT(*)::int FROM correspondents
`

func (q *Queries) CountCorrespondents(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countCorrespondents)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countTags = `-- name: CountTags :one
SELECT COUNT(*)::int FROM tags
`

func (q *Queries) CountTags(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countTags)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getDashboardDocumentStats = `-- name: GetDashboardDocumentStats :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE processing_status = 'completed')::int AS processed,
    COUNT(*) FILTER (WHERE processing_status = 'pending')::int AS pending,
    COUNT(*) FILTER (WHERE processing_status = 'failed')::int AS failed,
    COUNT(*) FILTER (WHERE created_at >= CURRENT_DATE)::int AS today
FROM documents
`

type GetDashboardDocumentStatsRow struct {
	Total     int32 `json:"total"`
	Processed int32 `json:"processed"`
	Pending   int32 `json:"pending"`
	Failed    int32 `json:"failed"`
	Today     int32 `json:"today"`
}

func (q *Queries) GetDashboardDocumentStats(ctx context.Context) (GetDashboardDocumentStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardDocumentStats)
	var i GetDashboardDocumentStatsRow
	err := row.Scan(
		&i.Total,
		&i.Processed,
		&i.Pending,
		&i.Failed,
		&i.Today,
	)
	return i, err
}

const getDashboardJobsToday = `-- name: GetDashboardJobsToday :one
SELECT COUNT(*)::int FROM jobs WHERE created_at >= CURRENT_DATE
`

func (q *Queries) GetDashboardJobsToday(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getDashboardJobsToday)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getDashboardQueueStats = `-- name: GetDashboardQueueStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending')::int AS pending,
    COUNT(*) FILTER (WHERE status = 'completed')::int AS completed,
    COUNT(*) FILTER (WHERE status = 'failed')::int AS failed,
    COUNT(*) FILTER (WHERE status = 'processing')::int AS processing
FROM jobs
`

type GetDashboardQueueStatsRow struct {
	Pending    int32 `json:"pending"`
	Completed  int32 `json:"completed"`
	Failed     int32 `json:"failed"`
	Processing int32 `json:"processing"`
}

func (q *Queries) GetDashboardQueueStats(ctx context.Context) (GetDashboardQueueStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardQueueStats)
	var i GetDashboardQueueStatsRow
	err := row.Scan(
		&i.Pending,
		&i.Completed,
		&i.Failed,
		&i.Processing,
	)
	return i, err
}

const getDashboardSourceStats = `-- name: GetDashboardSourceStats :one
SELECT
    (SELECT COUNT(*)::int FROM inboxes) AS inbox_total,
    (SELECT COUNT(*)::int FROM inboxes WHERE enabled = true) AS inbox_enabled,
    (SELECT COUNT(*)::int FROM network_sources) AS network_total,
    (SELECT COUNT(*)::int FROM network_sources WHERE enabled = true) AS network_enabled
`

type GetDashboardSourceStatsRow struct {
	InboxTotal     int32 `json:"inbox_total"`
	InboxEnabled   int32 `json:"inbox_enabled"`
	NetworkTotal   int32 `json:"network_total"`
	NetworkEnabled int32 `json:"network_enabled"`
}

func (q *Queries) GetDashboardSourceStats(ctx context.Context) (GetDashboardSourceStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSourceStats)
	var i GetDashboardSourceStatsRow
	err := row.Scan(
		&i.InboxTotal,
		&i.InboxEnabled,
		&i.NetworkTotal,
		&i.NetworkEnabled,
	)
	return i, err
}
