// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: example.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createExample = `-- name: CreateExample :one
INSERT INTO examples (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at
`

type CreateExampleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error) {
	row := q.db.QueryRow(ctx, createExample, arg.Name, arg.Description)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExample = `-- name: DeleteExample :exec
DELETE FROM examples WHERE id = $1
`

func (q *Queries) DeleteExample(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExample, id)
	return err
}

const getExample = `-- name: GetExample :one
SELECT id, name, description, created_at, updated_at FROM examples WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExample(ctx context.Context, id uuid.UUID) (Example, error) {
	row := q.db.QueryRow(ctx, getExample, id)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExamples = `-- name: ListExamples :many
SELECT id, name, description, created_at, updated_at FROM examples ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListExamplesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListExamples(ctx context.Context, arg ListExamplesParams) ([]Example, error) {
	rows, err := q.db.Query(ctx, listExamples, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Example{}
	for rows.Next() {
		var i Example
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExample = `-- name: UpdateExample :exec
UPDATE examples SET name = $1, description = $2, updated_at = NOW() WHERE id = $3
`

type UpdateExampleParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateExample(ctx context.Context, arg UpdateExampleParams) error {
	_, err := q.db.Exec(ctx, updateExample, arg.Name, arg.Description, arg.ID)
	return err
}
