// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addDocumentTag = `-- name: AddDocumentTag :exec
INSERT INTO document_tags (document_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (document_id, tag_id) DO NOTHING
`

type AddDocumentTagParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddDocumentTag(ctx context.Context, arg AddDocumentTagParams) error {
	_, err := q.db.Exec(ctx, addDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, color)
VALUES ($1, $2)
ON CONFLICT (name) DO NOTHING
RETURNING id, name, color, created_at
`

type CreateTagParams struct {
	Name  string  `json:"name"`
	Color *string `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getDocumentTags = `-- name: GetDocumentTags :many
SELECT t.id, t.name, t.color, t.created_at FROM tags t
INNER JOIN document_tags dt ON dt.tag_id = t.id
WHERE dt.document_id = $1
ORDER BY t.name
`

func (q *Queries) GetDocumentTags(ctx context.Context, documentID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getDocumentTags, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, name, color, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagsForDocuments = `-- name: GetTagsForDocuments :many
SELECT dt.document_id, t.id, t.name, t.color, t.created_at
FROM document_tags dt
INNER JOIN tags t ON t.id = dt.tag_id
WHERE dt.document_id = ANY($1::uuid[])
ORDER BY dt.document_id, t.name
`

type GetTagsForDocumentsRow struct {
	DocumentID uuid.UUID `json:"document_id"`
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	Color      *string   `json:"color"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) GetTagsForDocuments(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTagsForDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getTagsForDocuments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsForDocumentsRow{}
	for rows.Next() {
		var i GetTagsForDocumentsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithCounts = `-- name: ListTagsWithCounts :many
SELECT t.id, t.name, t.color, t.created_at, COUNT(dt.document_id)::int AS document_count
FROM tags t
LEFT JOIN document_tags dt ON t.id = dt.tag_id
GROUP BY t.id
ORDER BY t.name
`

type ListTagsWithCountsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Color         *string   `json:"color"`
	CreatedAt     time.Time `json:"created_at"`
	DocumentCount int32     `json:"document_count"`
}

func (q *Queries) ListTagsWithCounts(ctx context.Context) ([]ListTagsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listTagsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithCountsRow{}
	for rows.Next() {
		var i ListTagsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentTag = `-- name: RemoveDocumentTag :exec
DELETE FROM document_tags
WHERE document_id = $1 AND tag_id = $2
`

type RemoveDocumentTagParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveDocumentTag(ctx context.Context, arg RemoveDocumentTagParams) error {
	_, err := q.db.Exec(ctx, removeDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const searchTags = `-- name: SearchTags :many
SELECT id, name, color, created_at FROM tags
WHERE name ILIKE $1
ORDER BY name
LIMIT 10
`

func (q *Queries) SearchTags(ctx context.Context, name string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, searchTags, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTagsExcludingDocument = `-- name: SearchTagsExcludingDocument :many
SELECT t.id, t.name, t.color, t.created_at FROM tags t
WHERE t.name ILIKE $1
AND t.id NOT IN (
  SELECT tag_id FROM document_tags WHERE document_id = $2
)
ORDER BY t.name
LIMIT 10
`

type SearchTagsExcludingDocumentParams struct {
	Name       string    `json:"name"`
	DocumentID uuid.UUID `json:"document_id"`
}

func (q *Queries) SearchTagsExcludingDocument(ctx context.Context, arg SearchTagsExcludingDocumentParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, searchTagsExcludingDocument, arg.Name, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $2, color = $3
WHERE id = $1
RETURNING id, name, color, created_at
`

type UpdateTagParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Color *string   `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
